### ISSUE TITLE
Crash caused by write after end

### ISSUE THREAD

**Issue by davidrapin** [OpenMarshal/npm-WebDAV-Server#60]
Hi, 
first of all thank you for this amazing library. The code is of great quality and the examples from the doc help a lot.

details:
- I'm using v2.4.6 on the library, installed via npm.
- I'm running node v10.15.3 on linux (ubuntu 18)

I wrote a very tiny script based on an example to create a WebDav server to serve a single physical folder. The server works, but while exploring folders and reading files from a WebDav client on my server, the server crash with this message:

```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:572:17)
    at ServerResponse.write (_http_outgoing.js:567:10)
    at RangedStream.ondata (_stream_readable.js:689:20)
    at RangedStream.emit (events.js:189:13)
    at RangedStream.Readable.read (_stream_readable.js:487:10)
    at flow (_stream_readable.js:953:34)
    at ServerResponse.pipeOnDrainFunctionResult (_stream_readable.js:757:7)
    at ServerResponse.emit (events.js:189:13)
    at Socket.ondrain (internal/http.js:31:44)
    at Socket.emit (events.js:194:15)
Emitted 'error' event at:
    at writeAfterEndNT (_http_outgoing.js:634:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Here is the code of the server:
```js
const path = require('path');
const webdav = require('webdav-server').v2;

const userManager = new webdav.SimpleUserManager();
const user = userManager.addUser('test', 'test', false);

const privilegeManager = new webdav.SimplePathPrivilegeManager();
privilegeManager.setRights(user, '/', [ 'all' ]);

const server = new webdav.WebDAVServer({
  isVerbose: true,
  httpAuthentication: new webdav.HTTPDigestAuthentication(userManager, 'Default realm'),
  privilegeManager: privilegeManager,
  hostname: '::',
  port: 3030
});

function mount(server, target, folderPath) {
  return new Promise((resolve, reject) => {
    server.setFileSystem(
      target, 
      new webdav.PhysicalFileSystem(folderPath),
      (success) => {
        if (success) {
          console.log(`- mounted ${target} (${folderPath})`);
          resolve();
        } else {
          reject(`could not mount "${folderPath}"`); 
        }
      }
    );
  });
}

Promise.all([
  mount(server, '/folder1/', '/home/user1/folder1'),
  mount(server, '/folder2/', '/home/user1/folder2/')
]).then(() => {
  server.start(() => console.log('READY'));
}).catch((e) => {
  console.error('WebDav init failure: ' + e.message);
});
```

Any help is welcome :)

**Comment by AdrienCastex** [comment]
Hello,

Despite all the tests I made, I do not reproduce this error.
Please, can you tell me the procedure which leads to this error and the resources you are exploring ?
