### ISSUE TITLE
Context for ITestableUserManager and IListUserManager

### ISSUE THREAD

**Issue by btimby** [OpenMarshal/npm-WebDAV-Server#72]
In my situation, I need access to the HTTP request context in order to select the correct user. Specifically, this is a multi-domain set up, so I want access to the `Host` header within `ITestableUserManager.getUserByNamePassword()`. Since this is called from within `HTTPAuthentication.getUser()`, context is available.

I would like to create a PR that modifies the interfaces and implementations to provide `ctx` as an additional parameter to methods of `ITestableUserManager` and `IListUserManager` and make a corresponding change to `HTTPAuthentication.getUser()` to pass in the context. I can maintain backwards compatibility by duck typing the last two parameters.

I can also update the documentation to reflect this change.

Am I missing something? Is this change one that you would consider useful? Are any other changes necessary for the PR to be accepted?

Thanks.

**Comment by btimby** [comment]
Here is a first pass.

https://github.com/OpenMarshal/npm-WebDAV-Server/pull/73

**Comment by btimby** [comment]
A question, I am trying to install my fork into my project, my `package.json` contains:

```
"webdav-server": "git+https://git@github.com/btimby/npm-WebDAV-server.git#72f0631e401d9c706d2aa745d7b91c66303e661b",
```

But when I attempt to `require('webdav-server')` I get:

```
davd_1        | Error: Cannot find module '/node_modules/webdav-server/lib/index'. Please verify that the package.json has a valid "main" entry
davd_1        |     at tryPackage (internal/modules/cjs/loader.js:316:19)
davd_1        |     at Function.Module._findPath (internal/modules/cjs/loader.js:705:18)
davd_1        |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:969:27)
davd_1        |     at Function.Module._load (internal/modules/cjs/loader.js:864:27)
davd_1        |     at Module.require (internal/modules/cjs/loader.js:1044:19)
davd_1        |     at require (internal/modules/cjs/helpers.js:77:18)
davd_1        |     at Object.<anonymous> (/app/dav/davserver.js:3:16)
davd_1        |     at Module._compile (internal/modules/cjs/loader.js:1158:30)
davd_1        |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
davd_1        |     at Module.load (internal/modules/cjs/loader.js:1002:32)
davd_1        |     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
davd_1        |     at Module.require (internal/modules/cjs/loader.js:1044:19)
davd_1        |     at require (internal/modules/cjs/helpers.js:77:18)
davd_1        |     at Object.<anonymous> (/app/index.js:13:19)
davd_1        |     at Module._compile (internal/modules/cjs/loader.js:1158:30)
davd_1        |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
davd_1        |     at Module.load (internal/modules/cjs/loader.js:1002:32)
davd_1        |     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
davd_1        |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
davd_1        |     at internal/main/run_main_module.js:18:47
```

I am missing some step to make this an installable package, any tips?

**Comment by btimby** [comment]
Nevermind. I just implemented a new `HTTPBasicAuthentication`.
